# Generated by Django 3.1.3 on 2020-11-10 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal_record',
            fields=[
                ('meal_record_ID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='식사기록아이디')),
                ('date', models.DateField(verbose_name='입력날짜')),
                ('time', models.DateTimeField(verbose_name='입력시간')),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('photo_name', models.CharField(max_length=100, verbose_name='사진이름')),
                ('username', models.ForeignKey(db_column='사용자아이디', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_record',
            },
        ),
        migrations.CreateModel(
            name='Meal_record_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_ID', models.CharField(max_length=10, verbose_name='음식아이디')),
                ('food_name', models.CharField(max_length=50, verbose_name='음식명')),
                ('food_quantity', models.IntegerField(verbose_name='음식양')),
                ('food_kcal', models.IntegerField(verbose_name='음식열량')),
                ('carbohydrate_intake', models.IntegerField(verbose_name='탄수화물섭취량')),
                ('protein_intake', models.IntegerField(verbose_name='단백질섭취량')),
                ('fat_intake', models.IntegerField(verbose_name='지방섭취량')),
                ('meal_record_ID', models.ForeignKey(db_column='meal_record_ID', on_delete=django.db.models.deletion.CASCADE, to='diet.meal_record')),
            ],
            options={
                'db_table': 'meal_record_details',
            },
        ),
    ]
