# Generated by Django 3.1.3 on 2020-11-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_auto_20201112_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_record',
            name='photo_yolo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/yolo'),
        ),
        migrations.AlterField(
            model_name='meal_record',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
