# Generated by Django 3.1.3 on 2020-11-21 08:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_auto_20201121_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_record',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='입력날짜'),
        ),
        migrations.AlterField(
            model_name='meal_record',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='입력시간'),
        ),
    ]
