# Generated by Django 3.1.3 on 2020-11-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_auto_20201121_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal_record',
            old_name='photo_file',
            new_name='photo_origin',
        ),
    ]
