# Generated by Django 3.1.3 on 2020-11-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201110_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='PA',
            field=models.FloatField(choices=[(1.0, '비활동적'), (1.12, '저활동적'), (1.27, '활동적'), (1.45, '매우 활동적')], max_length=5, null=True, verbose_name='신체활동계수'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='diabetes_type',
            field=models.CharField(choices=[('제1형', 'tyep1_diabetes'), ('제2형', 'type2_diabetes'), ('임신', 'pregnant_diabetes'), ('기타', 'etc')], max_length=10, null=True, verbose_name='당뇨병유형'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='energy_needs',
            field=models.FloatField(max_length=5, null=True, verbose_name='에너지필요량'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='height',
            field=models.FloatField(max_length=5, null=True, verbose_name='키'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='weight',
            field=models.FloatField(max_length=5, null=True, verbose_name='몸무게'),
        ),
        migrations.AlterModelTable(
            name='user_profile',
            table='user_profiles',
        ),
    ]
